name: Cloud-Linker
on:
  workflow_dispatch:
    inputs:
      url:
        description: 'YouTube URL'
        required: true

jobs:
  get-link:
    runs-on: ubuntu-latest
    steps:
      - name: ツールをインストール
        run: pip install yt-dlp

      - name: 映像と音を合体させたURLを取得
        run: |
          echo "【準備完了！下のURLをコピーしてください】"
          yt-dlp -g -f "bestvideo[height<=720]+bestaudio/best[height<=720]/best" "${{ github.event.inputs.url }}"
